services:
  shortcat-bot:
    container_name: shortcat-bot
    image: ghcr.io/njayv/shortcat.pro:latest
    restart: unless-stopped
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 120 --cleanup # check every 2 minutes
    restart: unless-stopped
